const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmtMoney=new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0});
const fmtNum=new Intl.NumberFormat('es-CO',{maximumFractionDigits:0});
const fmt1=new Intl.NumberFormat('es-CO',{minimumFractionDigits:1,maximumFractionDigits:1});
const fmt2=new Intl.NumberFormat('es-CO',{minimumFractionDigits:2,maximumFractionDigits:2});
const RED='#e40521', INK='#111111', GRAY='#c9c9c4', GREEN='#138a61', PURPLE='#6b5bbd', AMBER='#b97800';
let charts={};
let state={perf:[],seg:[],ads:[],adPerf:[],segMap:new Map(),adPerfMap:new Map(),perfEnriched:[],current:[],segment:'Todos',fileName:'',minDate:'',maxDate:''};
const MODEL_PATTERNS=[['DIO DLX',/DIO[-_ ]?DLX/i],['PCX160',/PCX[-_ ]?160|PCX160/i],['NX190',/NX[-_ ]?190|NX190/i],['XR190L',/XR[-_ ]?190L|XR190L/i],['XR150L',/XR[-_ ]?150L|XR150L/i],['CB125F',/CB[-_ ]?125F|CB125F|CB125STD|CB125DLX/i],['CB100',/CB[-_ ]?100|CB100/i],['XRE300',/XRE[-_ ]?300|XRE300/i],['ADV160',/ADV[-_ ]?160|ADV160/i],['CB300F',/CB[-_ ]?300F|CB300F|CB300(?!\d)/i],['CB190R',/CB[-_ ]?190R|CB190R|CB190(?!\d)/i],['NT1100',/NT[-_ ]?1100|NT1100/i],['CB110',/CB[-_ ]?110|CB110/i],['NAVI',/\bNAVI\b|\bNAVY\b/i],['X-BLADE',/XBLADE|X[-_ ]?BLADE/i],['WAVE',/\bWAVE\b/i],['DREAM',/\bDREAM\b/i],['DIO',/\bDIO\b/i]];
function n(v){if(v===null||v===undefined||v==='')return 0;if(typeof v==='number')return Number.isFinite(v)?v:0;let x=Number(String(v).replace(/[^0-9.-]/g,''));return Number.isFinite(x)?x:0}
function s(v){return v===null||v===undefined?'':String(v).trim()}
function isOther(v){return !v||/OTRO|SIN CLASIFICAR/i.test(v)}
function classifyModel(...parts){const current=parts.find(v=>v&&!isOther(v));if(current)return current;const text=parts.join(' ');for(const [name,re] of MODEL_PATTERNS)if(re.test(text))return name;return 'OTRO / SIN CLASIFICAR'}
function excelDate(v){if(!v)return '';if(v instanceof Date&&!isNaN(v))return v.toISOString().slice(0,10);if(typeof v==='number'||/^\d+(\.0+)?$/.test(String(v))){const q=n(v);if(q>30000&&q<60000){const d=XLSX.SSF.parse_date_code(q);if(d)return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`}}const t=s(v);const m=t.match(/^(\d{4})-(\d{2})-(\d{2})/);if(m)return `${m[1]}-${m[2]}-${m[3]}`;const d=new Date(t);return isNaN(d)?'':d.toISOString().slice(0,10)}
function get(row,...keys){for(const k of keys)if(row[k]!==undefined&&row[k]!==null&&row[k]!=='')return row[k];return ''}
function boolFlag(v){return /^SI|YES|TRUE|1$/i.test(s(v))}
function audienceClass(row){let a=s(get(row,'Tipo audiencia'));if(a)return a;if(boolFlag(get(row,'Es RMK')))return 'RMK';if(boolFlag(get(row,'Es LKL')))return 'LKL';if(boolFlag(get(row,'Es BBDD')))return 'BBDD';if(boolFlag(get(row,'Es Intereses')))return 'Intereses';return 'Broad'}
function audienceGroup(row){const a=audienceClass(row);if(boolFlag(get(row,'Es RMK'))||/RMK|Remarketing/i.test(a))return 'RMK';if(boolFlag(get(row,'Es LKL'))||/LKL|Lookalike/i.test(a))return 'LKL';if(boolFlag(get(row,'Es BBDD'))||/BBDD|Custom Audience/i.test(a))return 'BBDD';if(boolFlag(get(row,'Es Intereses'))||/Interes/i.test(a))return 'Intereses';return 'Broad'}
function sheetRows(wb,name){const ws=wb.Sheets[name];return ws?XLSX.utils.sheet_to_json(ws,{defval:'',raw:true}):[]}
function showLoading(x){$('#loading').classList.toggle('show',x)}
async function loadFile(file){showLoading(true);await new Promise(r=>setTimeout(r,50));try{const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array',cellDates:true});state.fileName=file.name;state.perf=sheetRows(wb,'META_PERFORMANCE_DIA');state.seg=sheetRows(wb,'META_SEGMENTACIONES');state.ads=sheetRows(wb,'META_ANUNCIOS');state.adPerf=sheetRows(wb,'META_ADS_PERFORMANCE');if(!state.perf.length)throw new Error('No encontré la hoja META_PERFORMANCE_DIA.');prepareData();initFilters();renderAll();$('#dashboard').classList.remove('hidden');$('#statusDot').classList.add('ok');$('#statusText').textContent='Data cargada';$('#dataBig').textContent=file.name.replace(/\.xlsx?$/i,'');$('#uploadShell').style.gridTemplateColumns='1fr 1fr';}catch(e){console.error(e);alert('No pude leer el archivo: '+e.message)}finally{showLoading(false)}}
function prepareData(){state.segMap=new Map();state.seg.forEach(r=>{const id=s(get(r,'Ad Set ID'));if(!id)return;r.__model=classifyModel(get(r,'Modelo'),get(r,'Conjunto de anuncios'),get(r,'Campaña'));r.__audience=audienceClass(r);r.__group=audienceGroup(r);state.segMap.set(id,r)});state.adPerfMap=new Map(state.adPerf.map(r=>[s(get(r,'Ad ID')),r]));state.perfEnriched=state.perf.map(r=>{const adset=s(get(r,'Ad Set ID'));const seg=state.segMap.get(adset)||{};const date=excelDate(get(r,'Fecha'));const model=classifyModel(get(r,'Modelo'),get(r,'Conjunto'),get(r,'Campaña'),get(seg,'Modelo'));return {...r,__date:date,__model:model,__seg:seg,__audience:audienceClass(Object.assign({},seg,r)),__group:audienceGroup(Object.assign({},seg,r)),__delivery:s(get(r,'Optimization goal', 'Resultado principal'))};}).filter(r=>r.__date);const dates=state.perfEnriched.map(r=>r.__date).sort();state.minDate=dates[0]||'';state.maxDate=dates.at(-1)||'';$('#metaPeriod').textContent=state.minDate&&state.maxDate?`${state.minDate} → ${state.maxDate}`:'—';$('#metaAdsets').textContent=fmtNum.format(new Set(state.perfEnriched.map(r=>s(get(r,'Ad Set ID')))).size);$('#metaAds').textContent=fmtNum.format(new Set(state.ads.map(r=>s(get(r,'Ad ID'))).filter(Boolean)).size);$('#metaSeg').textContent=fmtNum.format(state.seg.length)}
function uniq(arr){return [...new Set(arr.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'es'))}
function setOptions(el,arr,all='Todos'){el.innerHTML=`<option value="">${all}</option>`+arr.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('')}
function initFilters(){setOptions($('#fModel'),uniq(state.perfEnriched.map(r=>r.__model)));setOptions($('#fCampaign'),uniq(state.perfEnriched.map(r=>s(get(r,'Campaña')))),'Todas');setOptions($('#fAudience'),uniq(state.perfEnriched.map(r=>r.__audience)));setOptions($('#fDelivery'),uniq(state.perfEnriched.map(r=>r.__delivery)));$('#fFrom').value=state.minDate;$('#fTo').value=state.maxDate;['fModel','fCampaign','fAudience','fDelivery','fFrom','fTo'].forEach(id=>$('#'+id).addEventListener('change',renderAll));$('#fInterest').addEventListener('input',debounce(renderAll,250));$('#trendGranularity').addEventListener('change',()=>renderOverview());$('#creativeSort').addEventListener('change',renderCreatives)}
function debounce(fn,ms){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}
function filterData(){const model=$('#fModel').value,camp=$('#fCampaign').value,aud=$('#fAudience').value,del=$('#fDelivery').value,from=$('#fFrom').value,to=$('#fTo').value,interest=$('#fInterest').value.trim().toLowerCase();state.current=state.perfEnriched.filter(r=>{if(model&&r.__model!==model)return false;if(camp&&s(get(r,'Campaña'))!==camp)return false;if(aud&&r.__audience!==aud)return false;if(del&&r.__delivery!==del)return false;if(from&&r.__date<from)return false;if(to&&r.__date>to)return false;if(state.segment!=='Todos'&&r.__group!==state.segment)return false;if(interest){const seg=r.__seg||{};const hay=(s(get(seg,'Intereses'))+' '+s(get(seg,'Behaviors'))+' '+s(get(seg,'Cargos laborales'))).toLowerCase();if(!hay.includes(interest))return false}return true})}
function agg(rows){const o={spend:0,impressions:0,reach:0,clicks:0,linkClicks:0,uniqueClicks:0,outbound:0,lpv:0,leads:0,results:0};rows.forEach(r=>{o.spend+=n(get(r,'Inversión'));o.impressions+=n(get(r,'Impresiones'));o.reach+=n(get(r,'Alcance diario','Alcance'));o.clicks+=n(get(r,'Clicks'));o.linkClicks+=n(get(r,'Link Clicks'));o.uniqueClicks+=n(get(r,'Unique Clicks'));o.outbound+=n(get(r,'Outbound Clicks'));o.lpv+=n(get(r,'Landing Page Views'));o.leads+=n(get(r,'Leads'));o.results+=n(get(r,'Resultados'))});o.cpl=o.leads?o.spend/o.leads:0;o.ctr=o.impressions?o.clicks/o.impressions*100:0;o.cpc=o.clicks?o.spend/o.clicks:0;o.cpm=o.impressions?o.spend/o.impressions*1000:0;o.freq=o.reach?o.impressions/o.reach:0;o.cvr=o.linkClicks?o.leads/o.linkClicks*100:0;o.lpvRate=o.linkClicks?o.lpv/o.linkClicks*100:0;return o}
function groupBy(rows,keyFn){const m=new Map();rows.forEach(r=>{const k=keyFn(r)||'Sin clasificar';if(!m.has(k))m.set(k,[]);m.get(k).push(r)});return [...m.entries()].map(([key,rs])=>({key,rows:rs,...agg(rs)}))}
function renderAll(){filterData();renderOverview();renderAudiences();renderCampaigns();renderCreatives();renderHealth()}
